<?php

namespace EntityBundle\Repository;

/**
 * ProfessionalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfessionalRepository extends \Doctrine\ORM\EntityRepository
{
}
